### ISSUE TITLE
Error when importing

### ISSUE THREAD

**Issue by wwzh26** [PaddleCV-SIG/PaddleRS#53] opened 2022-04-15 10:11 UTC
The same error has been reported when importing paddlers. I have tried many times to create a new virtual environment and reinstall it, but it still does not solve it. Is there a better solution? Thank you very much for your help.
![image](https://user-images.githubusercontent.com/90379520/163558892-9599a0fa-c92c-4397-974c-6fb6b6f642ce.png)

**Comment by geoyee** [comment] 2022-04-16 01:07
Thank you for your issue 😃 . I guess the problem is `numpy` or `lap`, maybe you can try the following methods:
- Check your `numpy`'s version, maybe you can try to re-install `numpy` or use `pip install numpy -U` to upgrade your `numpy`.
- Check the number of `lap`, and use `pip uninstall lap` to uninstall redundant `lap`.

**Comment by wwzh26** [comment] 2022-04-17 03:18
Thanks for your reply.I found the past existing lab version is 0.4.0.The paddlers version I use is 2.2.2, may I ask which version of LAB I should reinstall？



在 2022-04-16 09:07:25，"Yizhou Chen" ***@***.***> 写道：

Thank you for your issue 😃 . I guess the problem is numpy or lap, maybe you can try the following methods:

Check your numpy's version, maybe you can try to re-install numpy or use pip install numpy -U to upgrade your numpy.
Check the number of lap, and use pip uninstall lap to uninstall redundant 'lap'.

**Comment by wwzh26** [comment] 2022-04-17 03:39
Lap 0.5.dev0. By reinstalling lab,the problem has been solved.Thanks for your help!!



在 2022-04-16 09:07:25，"Yizhou Chen" ***@***.***> 写道：

Thank you for your issue 😃 . I guess the problem is numpy or lap, maybe you can try the following methods:

Check your numpy's version, maybe you can try to re-install numpy or use pip install numpy -U to upgrade your numpy.
Check the number of lap, and use pip uninstall lap to uninstall redundant 'lap'.

**Comment by geoyee** [comment] 2022-04-18 08:58
NP, if you solve this problem, can I close this issue 😃 .

**Closed as completed** 2022-06-20 13:51 UTC
Labels: solved

**Comment by wwzh26** [comment] 2022-10-11 08:24
Sure.Thank you for your help.



在 2022-04-18 16:58:17，"Yizhou Chen" ***@***.***> 写道：

NP, if you solve this problem, can I close this issue 😃 .
